#
# Copyright (c) 2005-2006 Hewlett-Packard Development Company, L.P.
# Contributed by Stephane Eranian <eranian@hpl.hp.com>
#
obj-$(CONFIG_PERFMON) = perfmon.o perfmon_rw.o perfmon_res.o perfmon_fmt.o  \
			perfmon_pmu.o perfmon_sysfs.o perfmon_syscalls.o    \
			perfmon_file.o perfmon_ctxsw.o perfmon_intr.o	    \
			perfmon_dfl_smpl.o perfmon_sets.o perfmon_debugfs.o \
			perfmon_hotplug.o perfmon_msg.o
